#!/usr/bin/env python3
"""Generate oled_anim.h - the placeholder animation for the right half.

A heart that beats, with small hearts drifting up past it to give the tall
canvas something to do above and below. Eight frames, each filling the whole
64 x 128 canvas, so each one is 1024 bytes in page format.

The frames are a seamless loop: the beat is two squeezes per cycle, and the
small hearts wrap off the top back to the bottom.

Run from anywhere; it writes oled_anim.h next to itself. Pure stdlib.
"""

import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "oled_anim.h")

W, H = 64, 128
FRAMES = 8
STEPS = 6          # samples per pixel along each axis, for tidier edges


def heart_mask_grid():
    """Boolean mask of the classic heart curve, plus its bounding box."""
    N = 260
    span = 1.6
    grid = []
    min_u = max_u = min_v = max_v = 0.0
    first = True
    for j in range(N):
        v = span - 2 * span * j / (N - 1)      # +v is up
        row = []
        for i in range(N):
            u = -span + 2 * span * i / (N - 1)
            q = (u * u + v * v - 1.0) ** 3 - u * u * v * v * v
            inside = q <= 0.0
            row.append(inside)
            if inside:
                if first:
                    min_u = max_u = u
                    min_v = max_v = v
                    first = False
                min_u, max_u = min(min_u, u), max(max_u, u)
                min_v, max_v = min(min_v, v), max(max_v, v)
        grid.append(row)
    return grid, (min_u, max_u, min_v, max_v), span, N


GRID, (MIN_U, MAX_U, MIN_V, MAX_V), SPAN, N = heart_mask_grid()
HEART_W = MAX_U - MIN_U
HEART_H = MAX_V - MIN_V
CENTRE_U = (MIN_U + MAX_U) / 2
CENTRE_V = (MIN_V + MAX_V) / 2


def in_heart(u, v):
    i = (u + SPAN) / (2 * SPAN) * (N - 1)
    j = (SPAN - v) / (2 * SPAN) * (N - 1)
    i = min(max(int(round(i)), 0), N - 1)
    j = min(max(int(round(j)), 0), N - 1)
    return GRID[j][i]


# Two beats per loop, each a fast squeeze then a slower release, so it reads
# as a heartbeat rather than a sine wobble.
SCALES = [1.00, 1.14, 1.05, 0.98, 1.00, 1.12, 1.03, 0.97]

# Small hearts drifting up past the big one: (width in px, centre x, start y,
# px per frame). They give the tall canvas something to do either side of the
# heart, which would otherwise leave a lot of empty black above and below.
MINIS = [
    (9.0, 11.0, 118.0, 2.6),
    (7.0, 52.0, 44.0, 3.4),
    (6.0, 25.0, 76.0, 1.9),
    (8.0, 53.0, 104.0, 2.9),
]


def heart_at(x, y, cx, cy, width):
    """Is canvas pixel (x, y) inside a heart of `width` px centred on (cx, cy)?"""
    ppu = width / HEART_W
    u = (x + 0.5 - cx) / ppu + CENTRE_U
    v = (cy - (y + 0.5)) / ppu + CENTRE_V
    return in_heart(u, v)


def frame(t):
    """One 64x128 frame of 0/1 pixels, row-major, (0,0) top-left."""
    # Fit the heart to the canvas, then centre its bounding box on the panel.
    # The widest beat still has to clear the edges, hence the 12 px of slack.
    max_w = W - 12.0
    max_h = H * 0.60
    width = min(max_w, max_h * HEART_W / HEART_H) * SCALES[t % len(SCALES)]
    cx, cy = W / 2.0, H / 2.0

    # Where each small heart is this frame; they wrap from the top back to the
    # bottom so the loop is seamless.
    minis = []
    for size, mx, my, speed in MINIS:
        span = H + 2 * size
        minis.append((size, mx, ((my - speed * t) % span) - size))

    rows = [[0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            if heart_at(x, y, cx, cy, width):
                rows[y][x] = 1
                continue
            for size, mx, my in minis:
                if heart_at(x, y, mx, my, size):
                    rows[y][x] = 1
                    break
    return rows


def pack(rows):
    """Page format: 16 pages of 64 bytes, LSB of each byte is the top row."""
    out = bytearray()
    for page in range(H // 8):
        for x in range(W):
            byte = 0
            for bit in range(8):
                if rows[page * 8 + bit][x]:
                    byte |= 1 << bit
            out.append(byte)
    return out


def main():
    frames = [pack(frame(t)) for t in range(FRAMES)]
    for i, f in enumerate(frames):
        assert len(f) == W * H // 8, (i, len(f))

    with open(OUT, "w") as fh:
        fh.write("// Generated by make_anim.py - do not edit by hand.\n")
        fh.write("// %d frames of %dx%d px, %d bytes each (%d in total).\n"
                 % (FRAMES, W, H, len(frames[0]), FRAMES * len(frames[0])))
        fh.write("#pragma once\n\n")
        fh.write("#define SOFLE_ANIM_FRAMES %d\n\n" % FRAMES)
        fh.write("static const char PROGMEM oled_anim[SOFLE_ANIM_FRAMES][%d] = {\n" % len(frames[0]))
        for i, data in enumerate(frames):
            fh.write("    { // frame %d\n" % i)
            for k in range(0, len(data), 16):
                fh.write("        " + ",".join("0x%02x" % b for b in data[k:k + 16]) + ",\n")
            fh.write("    },\n")
        fh.write("};\n")

    lit = [sum(bin(b).count("1") for b in f) for f in frames]
    print("wrote %s" % OUT)
    print("%d frames, %d bytes each, %d bytes total" % (FRAMES, len(frames[0]), FRAMES * len(frames[0])))
    print("lit pixels per frame: %s" % lit)


if __name__ == "__main__":
    main()
