#!/usr/bin/env python3
"""Generate oled_bigfont.h - QMK's 6x8 font doubled, for the layer banner.

The OLED driver declares its `font[]` table `static`, so keymap.c cannot reach
it. Rather than carry a copy of the whole 1.5 KB table, this emits only the
glyphs the banner can print: space, A-Z and 0-9.

Each glyph becomes 12 x 16 px in page format: 2 pages x 12 columns = 24 bytes.
The glyphs are a plain 2x nearest-neighbour upscale, so they are blocky at this
size, which is the look you want at 12 px per character anyway.

Run from anywhere; it reads QMK's font out of the tree it lives in and writes
oled_bigfont.h next to itself. There is nothing to install.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
# .../keyboards/sofle_pico/keymaps/default -> the root of the QMK tree.
QMK = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
OUT = os.path.join(HERE, "oled_bigfont.h")

FONT_W = 6       # one source glyph: 6 columns, 8 rows, one byte per column
SCALE = 2
GW = FONT_W * SCALE  # 12 px wide
GH = 8 * SCALE       # 16 px tall

CHARSET = " " + "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "0123456789"


def load_font():
    src = open(os.path.join(QMK, "drivers", "oled", "glcdfont.c")).read()
    body = re.search(r"font\[\]\s*(?:PROGMEM\s*)?=\s*\{(.*?)\};", src, re.S).group(1)
    # Each entry carries a trailing "// 0x4D M" comment whose hex is not data.
    body = re.sub(r"//[^\n]*", "", body)
    data = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", body)]
    assert len(data) % FONT_W == 0, "font table is not a whole number of glyphs"
    return data


def upscale(font, ch):
    """Return GH rows of GW bits, (0,0) top-left, for one character."""
    off = ord(ch) * FONT_W
    glyph = font[off : off + FONT_W]
    rows = []
    for r in range(GH):
        src_bit = r // SCALE
        row = []
        for c in range(GW):
            row.append((glyph[c // SCALE] >> src_bit) & 1)
        rows.append(row)
    return rows


def pack(rows):
    """GH x GW bits -> page format: (GH/8) pages of GW bytes, LSB = top row."""
    out = bytearray()
    for page in range(GH // 8):
        for c in range(GW):
            byte = 0
            for bit in range(8):
                if rows[page * 8 + bit][c]:
                    byte |= 1 << bit
            out.append(byte)
    return out


def main():
    font = load_font()
    assert len(font) >= 224 * FONT_W, "font table looks short"

    glyphs = {ch: pack(upscale(font, ch)) for ch in CHARSET}
    total = sum(len(g) for g in glyphs.values())

    with open(OUT, "w") as fh:
        fh.write("// Generated by make_bigfont.py - do not edit by hand.\n")
        fh.write("// QMK's 6x8 font scaled %dx: %d x %d px, %d bytes per glyph.\n"
                 % (SCALE, GW, GH, GH // 8 * GW))
        fh.write("#pragma once\n\n")
        fh.write("#define OLED_BIGFONT_W %d\n" % GW)
        fh.write("#define OLED_BIGFONT_H %d\n" % GH)
        fh.write("#define OLED_BIGFONT_BYTES %d\n\n" % (GH // 8 * GW))
        fh.write("// Index of a character in oled_bigfont[]; -1 means no glyph.\n")
        fh.write("static const char PROGMEM oled_bigfont_index[] = \"%s\";\n\n" % CHARSET)
        fh.write("static const char PROGMEM oled_bigfont[%d][OLED_BIGFONT_BYTES] = {\n" % len(CHARSET))
        for ch in CHARSET:
            data = glyphs[ch]
            name = {32: "space"}.get(ord(ch), ch)
            body = ",".join("0x%02x" % b for b in data)
            fh.write("    {%s}, // '%s'\n" % (body, name))
        fh.write("};\n")

    print("wrote %s (%d glyphs, %d bytes of font data)" % (OUT, len(CHARSET), total))


if __name__ == "__main__":
    main()
