/* qmk_host.h -- host-side (macOS/POSIX) stand-in for the parts of QMK's
 * `quantum/rgb_matrix/rgb_matrix.h` + `keyboard.h` that the RGB Matrix effect
 * sources need in order to compile and run as a plain native C program.
 *
 * Nothing in here re-implements an effect: the effect maths, the effect
 * runners and `hsv_to_rgb()` all come from the real files in this repository.
 * This header only provides types, macros and declarations, and those are
 * copied from the real QMK headers (provenance is marked at each block).
 *
 * What is intentionally *not* here (and why) is documented in README.md.
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* --------------------------------------------------------------------------
 * 1. Real, compiled-in configuration for sofle_pico.
 *
 * `info_config.h` is generated by the QMK build system into
 * `.build/obj_sofle_pico_default/src/`; using it means we inherit the exact
 * RGB_MATRIX_LED_COUNT / MATRIX_ROWS / MATRIX_COLS / RGB_MATRIX_DEFAULT_SPD /
 * RGB_MATRIX_MAXIMUM_BRIGHTNESS and the exact list of ENABLE_RGB_MATRIX_*
 * effects instead of hand-copying them (and getting them wrong).
 * ------------------------------------------------------------------------ */
#include "info_config.h"

/* The firmware is a split keyboard and therefore DOES define
 * `RGB_MATRIX_SPLIT { 29, 29 }`.  We deliberately drop it: without it a single
 * process renders all 58 LEDs in one go, which is bit-for-bit what the two
 * halves do separately once their buffers are concatenated, and it keeps
 * `is_keyboard_left()` / `is_keyboard_master()` out of the harness.
 * See README.md ("deviations"). */
#ifdef RGB_MATRIX_SPLIT
#    undef RGB_MATRIX_SPLIT
#endif

/* QMK derives RGB_MATRIX_FRAMEBUFFER_EFFECTS and RGB_MATRIX_KEYPRESSES from the
 * ENABLE_RGB_MATRIX_* list in quantum/rgb_matrix/post_config.h, which is one of
 * the firmware's `-include` files (see
 * .build/obj_sofle_pico_default/cflags.txt).  Use the real file rather than
 * hard-coding the conclusion. */
#include "rgb_matrix/post_config.h"
#if !defined(RGB_MATRIX_FRAMEBUFFER_EFFECTS) || !defined(RGB_MATRIX_KEYPRESSES)
#    error "harness: quantum/rgb_matrix/post_config.h enabled neither/both -- the firmware enables both for this keyboard"
#endif

/* From keyboards/sofle_pico/config.h:57 (it is not a keyboard.json setting, so
 * it does not appear in info_config.h): this keyboard overrides the
 * typing-heatmap decay delay from the 25 ms default in typing_heatmap_anim.h. */
#ifndef RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS
#    define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 50
#endif

/* Real QMK types: colour.h / rgb_matrix_types.h pull in util.h, lib8tion's
 * bits.h + bitwise.h.  `rgb_matrix_types.h` derives
 * RGB_MATRIX_KEYREACTIVE_ENABLED from RGB_MATRIX_KEYPRESSES above. */
#include "rgb_matrix_types.h"

/* lib/lib8tion/trig8.h defines `sin8_avr()` with AVR inline asm (register
 * constraint "=d") that Apple clang refuses to parse for arm64, even though the
 * function is dead outside `#if defined(__AVR__)`.  generated/trig8.h is the
 * same file with that one definition wrapped in `#if defined(__AVR__)`
 * (prepare_effects.py; verified pure insertion).
 *
 * It has to be included *before* lib8tion.h (whose own `#include "trig8.h"`
 * then finds the include guard already set), and trig8.h is written in terms of
 * LIB8STATIC, which lib8tion.h would normally define first -- so those two
 * macros are defined here exactly as lib8tion.h:170-171 does; its own
 * identical #defines are then harmless. */
#define LIB8STATIC static inline
#define LIB8STATIC_ALWAYS_INLINE static inline
#include "generated/trig8.h"
#include "lib8tion.h"

/* --------------------------------------------------------------------------
 * 2. Macro block lifted from `quantum/rgb_matrix/rgb_matrix.h`.
 *    Everything that does not drag in keyboard.h / rgb_matrix_drivers.h /
 *    chibios is copied as-is; see README.md.
 * ------------------------------------------------------------------------ */

#ifndef RGB_MATRIX_MAXIMUM_BRIGHTNESS /* already set by info_config.h */
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS UINT8_MAX
#endif

/* rgb_matrix.h:36-50 verbatim */
#ifndef RGB_MATRIX_HUE_STEP
#    define RGB_MATRIX_HUE_STEP 8
#endif
#ifndef RGB_MATRIX_SAT_STEP
#    define RGB_MATRIX_SAT_STEP 16
#endif
#ifndef RGB_MATRIX_VAL_STEP
#    define RGB_MATRIX_VAL_STEP 16
#endif
#ifndef RGB_MATRIX_SPD_STEP
#    define RGB_MATRIX_SPD_STEP 16
#endif
#ifndef RGB_MATRIX_DEFAULT_ON
#    define RGB_MATRIX_DEFAULT_ON true
#endif
/* RGB_MATRIX_DEFAULT_MODE comes from info_config.h */
#ifndef RGB_MATRIX_DEFAULT_HUE
#    define RGB_MATRIX_DEFAULT_HUE 0
#endif
#ifndef RGB_MATRIX_DEFAULT_SAT
#    define RGB_MATRIX_DEFAULT_SAT UINT8_MAX
#endif
#ifndef RGB_MATRIX_DEFAULT_VAL
#    define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#endif
/* RGB_MATRIX_DEFAULT_SPD comes from info_config.h */
#ifndef RGB_MATRIX_DEFAULT_FLAGS
#    define RGB_MATRIX_DEFAULT_FLAGS LED_FLAG_ALL
#endif
#ifndef RGB_MATRIX_LED_FLUSH_LIMIT
#    define RGB_MATRIX_LED_FLUSH_LIMIT 16
#endif
#ifndef RGB_MATRIX_TIMEOUT
#    define RGB_MATRIX_TIMEOUT 0
#endif

/* rgb_matrix.h:89-91 defines
 *     #define RGB_MATRIX_LED_PROCESS_LIMIT ((RGB_MATRIX_LED_COUNT + 4) / 5)
 * i.e. 12 for this keyboard, which makes the firmware render the matrix in
 * five `iter` steps of 12 LEDs.
 *
 * The harness runs one full-matrix step per frame (`iter == 0`,
 * led_min/led_max == {0, 58}), so we pin the limit to the LED count.  For the
 * eight effects modelled here this is output-identical to the five-step
 * firmware loop (see README.md); keeping the symbol non-zero is required
 * because typing_heatmap uses it as a loop bound. */
#ifndef RGB_MATRIX_LED_PROCESS_LIMIT
#    define RGB_MATRIX_LED_PROCESS_LIMIT RGB_MATRIX_LED_COUNT
#endif

struct rgb_matrix_limits_t {
    uint8_t led_min_index;
    uint8_t led_max_index;
};

struct rgb_matrix_limits_t rgb_matrix_get_limits(uint8_t iter);

/* rgb_matrix.h:100-107 verbatim */
#define RGB_MATRIX_USE_LIMITS_ITER(min, max, iter)                   \
    struct rgb_matrix_limits_t limits = rgb_matrix_get_limits(iter); \
    uint8_t                    min    = limits.led_min_index;        \
    uint8_t                    max    = limits.led_max_index;        \
    (void)min;                                                       \
    (void)max;

#define RGB_MATRIX_USE_LIMITS(min, max) RGB_MATRIX_USE_LIMITS_ITER(min, max, params->iter)

/* rgb_matrix.h:109-112 verbatim */
#define RGB_MATRIX_INDICATOR_SET_COLOR(i, r, g, b) \
    if (i >= led_min && i < led_max) {             \
        rgb_matrix_set_color(i, r, g, b);          \
    }

/* rgb_matrix.h:114-115 verbatim */
#define RGB_MATRIX_TEST_LED_FLAGS() \
    if (!HAS_ANY_FLAGS(g_led_config.flags[i], params->flags)) continue

/* rgb_matrix.h:283-293 with the RGB_MATRIX_SPLIT branch removed (we never
 * define RGB_MATRIX_SPLIT), which leaves exactly the firmware's
 * non-split / right-half behaviour. */
static inline bool rgb_matrix_check_finished_leds(uint8_t led_idx) {
    return led_idx < RGB_MATRIX_LED_COUNT;
}

/* --------------------------------------------------------------------------
 * 3. `enum rgb_matrix_effects` -- built by the very same macro machinery the
 *    firmware uses (rgb_matrix.h:117-146), so `mode` numbers in the JSON are
 *    the firmware's own mode numbers.
 * ------------------------------------------------------------------------ */
enum rgb_matrix_effects {
    RGB_MATRIX_NONE = 0,

#define RGB_MATRIX_EFFECT(name, ...) RGB_MATRIX_##name,
#include "rgb_matrix_effects.inc"
#undef RGB_MATRIX_EFFECT

    RGB_MATRIX_EFFECT_MAX
};

/* --------------------------------------------------------------------------
 * 4. Declarations, mirroring rgb_matrix.h:151-167 / 295-304 for the parts of
 *    the framework the effect sources call.  They must be visible *before*
 *    the effect implementation headers are included (same as in
 *    rgb_matrix.c, where rgb_matrix.h provides them).
 * ------------------------------------------------------------------------ */

void    rgb_matrix_set_color(int index, uint8_t red, uint8_t green, uint8_t blue);
void    rgb_matrix_set_color_all(uint8_t red, uint8_t green, uint8_t blue);
uint8_t rgb_matrix_map_row_column_to_led(uint8_t row, uint8_t column, uint8_t *led_i);
uint8_t rgb_matrix_map_row_column_to_led_kb(uint8_t row, uint8_t column, uint8_t *led_i);
void    rgb_matrix_handle_key_event(uint8_t row, uint8_t col, bool pressed);
rgb_t   rgb_matrix_hsv_to_rgb(hsv_t hsv);

/* Defined by typing_heatmap_anim.h (real QMK code); declared here for the same
 * reason rgb_matrix.c can call it. */
void process_rgb_matrix_typing_heatmap(uint8_t row, uint8_t col);

extern rgb_config_t rgb_matrix_config;
extern uint32_t     g_rgb_timer;
extern led_config_t g_led_config;
extern const led_point_t k_rgb_matrix_center;
#ifdef RGB_MATRIX_KEYREACTIVE_ENABLED
extern last_hit_t g_last_hit_tracker;
#endif
#ifdef RGB_MATRIX_FRAMEBUFFER_EFFECTS
extern uint8_t g_rgb_frame_buffer[MATRIX_ROWS][MATRIX_COLS];
#endif

/* --------------------------------------------------------------------------
 * 5. Host stand-ins for the platform timing API.
 *
 * On the real keyboard these come from `platforms/chibios/timer.c` /
 * `quantum/sync_timer.c`; here they are driven by the harness' virtual
 * millisecond clock.  Prototypes match `platforms/timer.h` exactly.
 * ------------------------------------------------------------------------ */
uint16_t timer_read(void);
uint16_t timer_elapsed(uint16_t last);
uint32_t get_millisecond_timer(void); /* declared by lib8tion.h, defined here */
